server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordersfood?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&requireSSL=false&useSSL=false
    username: root
    password: root
    initialization-mode: always
    platform: mysql
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin